"""Rebuild one day's analysis summary from the data as it stood then.

Normal analysis always picks each guild's newest workbook, so once newer data
is collected an old day's ``summary_<date>.xlsx`` can no longer be regenerated by
``analyze.py`` -- and if the collection session was never reset, a new run even
overwrites the old day's file with the newer data.

This tool reconstructs a specific collection day cleanly:

* Only guilds that actually have a ``guild_*_<date>.xlsx`` file are included
  (= exactly the guilds whose list was made that day).
* Each guild is analyzed "as of" that date, so growth-vs-previous compares
  against the prior collection, not against data collected afterwards.

Usage:
    python -m src.rebuild_summary 2026-06-20
    python -m src.rebuild_summary 2026-06-20 2026-06-27
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    from . import analyze
    from .analyze import DATA_DIR, ANALYSIS_DIR
except ImportError:  # 直接実行された場合
    import analyze  # type: ignore
    from analyze import DATA_DIR, ANALYSIS_DIR  # type: ignore


def guild_dirs_collected_on(target_date: str) -> list[Path]:
    """Guild dirs that have a workbook dated exactly ``target_date``."""

    dirs: list[Path] = []
    for guild_dir in sorted(DATA_DIR.iterdir(), key=lambda p: p.name):
        if not guild_dir.is_dir():
            continue
        if any(guild_dir.glob(f"guild_*_{target_date}.xlsx")):
            dirs.append(guild_dir)
    return dirs


def rebuild(target_date: str) -> Path:
    settings = analyze.load_settings()
    guild_dirs = guild_dirs_collected_on(target_date)
    if not guild_dirs:
        raise SystemExit(f"{target_date} に収集されたギルドが見つかりません。")

    metrics: list[dict] = []
    failures: list[tuple[str, str]] = []
    for guild_dir in guild_dirs:
        try:
            metrics.append(analyze.analyze_guild(guild_dir, settings, as_of_date=target_date))
        except Exception as exc:  # noqa: BLE001 - keep going per guild
            failures.append((guild_dir.name, str(exc)))

    analyze.enrich_comparison_metrics(metrics)

    output_file = ANALYSIS_DIR / f"summary_{target_date}.xlsx"
    analyze.write_analysis_workbook(metrics, settings, output_file)

    print(f"[{target_date}] 成功 {len(metrics)} ギルド / 失敗 {len(failures)} ギルド")
    for name, reason in failures:
        print(f"  - 失敗: {name}: {reason}")
    print(f"  出力: {output_file}")
    return output_file


def main() -> None:
    dates = sys.argv[1:]
    if not dates:
        raise SystemExit("使い方: python -m src.rebuild_summary YYYY-MM-DD [YYYY-MM-DD ...]")
    for target_date in dates:
        rebuild(target_date)


if __name__ == "__main__":
    main()
